{ pkgs, config, ... }:

{
  gtk = {
    enable = true;

    font.name = "Helvetica Neue LT Std 11";

    cursorTheme.package = pkgs.bibata-cursors;
    cursorTheme.name = "Bibata-Modern-Ice";

    theme.package = pkgs.adw-gtk3;
    theme.name = "adw-gtk3";
  };

  home.file.".config/gtk-4.0/gtk.css".text = ''
    @define-color accent_color #${config.colorScheme.colors.base0D};
    @define-color accent_bg_color mix(#${config.colorScheme.colors.base0D}, #${config.colorScheme.colors.base01}, 0.3);
    @define-color accent_fg_color #${config.colorScheme.colors.base07};
    @define-color destructive_color #${config.colorScheme.colors.base0D};
    @define-color destructive_bg_color mix(#${config.colorScheme.colors.base0D}, #${config.colorScheme.colors.base01}, 0.3);
    @define-color destructive_fg_color #${config.colorScheme.colors.base07};
    @define-color success_color #${config.colorScheme.colors.base0B};
    @define-color success_bg_color #${config.colorScheme.colors.base0B};
    @define-color success_fg_color #${config.colorScheme.colors.base07};
    @define-color warning_color #${config.colorScheme.colors.base0A};
    @define-color warning_bg_color #${config.colorScheme.colors.base09};
    @define-color warning_fg_color rgba(0, 0, 0, 0.8);
    @define-color error_color #${config.colorScheme.colors.base0F};
    @define-color error_bg_color mix(#${config.colorScheme.colors.base0D}, #${config.colorScheme.colors.base01}, 0.3);
    @define-color error_fg_color #${config.colorScheme.colors.base07};
    @define-color window_bg_color #${config.colorScheme.colors.base01};
    @define-color window_fg_color #${config.colorScheme.colors.base07};
    @define-color view_bg_color #${config.colorScheme.colors.base01};
    @define-color view_fg_color #${config.colorScheme.colors.base07};
    @define-color headerbar_bg_color mix(#${config.colorScheme.colors.base01},black,0.2);
    @define-color headerbar_fg_color #${config.colorScheme.colors.base07};
    @define-color headerbar_border_color #${config.colorScheme.colors.base07};
    @define-color headerbar_backdrop_color @window_bg_color;
    @define-color headerbar_shade_color rgba(0, 0, 0, 0.36);
    @define-color card_bg_color rgba(255, 255, 255, 0.08);
    @define-color card_fg_color #${config.colorScheme.colors.base07};
    @define-color card_shade_color rgba(0, 0, 0, 0.36);
    @define-color dialog_bg_color #${config.colorScheme.colors.base03};
    @define-color dialog_fg_color #${config.colorScheme.colors.base07};
    @define-color popover_bg_color #${config.colorScheme.colors.base03};
    @define-color popover_fg_color #${config.colorScheme.colors.base07};
    @define-color shade_color rgba(0,0,0,0.36);
    @define-color scrollbar_outline_color rgba(0,0,0,0.5);
    @define-color blue_1 #${config.colorScheme.colors.base0D};
    @define-color blue_2 #${config.colorScheme.colors.base0D};
    @define-color blue_3 #${config.colorScheme.colors.base0D};
    @define-color blue_4 #${config.colorScheme.colors.base0D};
    @define-color blue_5 #${config.colorScheme.colors.base0D};
    @define-color green_1 #${config.colorScheme.colors.base0B};
    @define-color green_2 #${config.colorScheme.colors.base0B};
    @define-color green_3 #${config.colorScheme.colors.base0B};
    @define-color green_4 #${config.colorScheme.colors.base0B};
    @define-color green_5 #${config.colorScheme.colors.base0B};
    @define-color yellow_1 #${config.colorScheme.colors.base0A};
    @define-color yellow_2 #${config.colorScheme.colors.base0A};
    @define-color yellow_3 #${config.colorScheme.colors.base0A};
    @define-color yellow_4 #${config.colorScheme.colors.base0A};
    @define-color yellow_5 #${config.colorScheme.colors.base0A};
    @define-color orange_1 #${config.colorScheme.colors.base09};
    @define-color orange_2 #${config.colorScheme.colors.base09};
    @define-color orange_3 #${config.colorScheme.colors.base09};
    @define-color orange_4 #${config.colorScheme.colors.base09};
    @define-color orange_5 #${config.colorScheme.colors.base09};
    @define-color red_1 #${config.colorScheme.colors.base0F};
    @define-color red_2 #${config.colorScheme.colors.base0F};
    @define-color red_3 #${config.colorScheme.colors.base0F};
    @define-color red_4 #${config.colorScheme.colors.base0F};
    @define-color red_5 #${config.colorScheme.colors.base0F};
    @define-color purple_1 #${config.colorScheme.colors.base0E};
    @define-color purple_2 #${config.colorScheme.colors.base0E};
    @define-color purple_3 #${config.colorScheme.colors.base0E};
    @define-color purple_4 #${config.colorScheme.colors.base0E};
    @define-color purple_5 #${config.colorScheme.colors.base0E};
    @define-color brown_1 #${config.colorScheme.colors.base0F};
    @define-color brown_2 #${config.colorScheme.colors.base0F};
    @define-color brown_3 #${config.colorScheme.colors.base0F};
    @define-color brown_4 #${config.colorScheme.colors.base0F};
    @define-color brown_5 #${config.colorScheme.colors.base0F};
    @define-color light_1 #${config.colorScheme.colors.base04};
    @define-color light_2 #${config.colorScheme.colors.base05};
    @define-color light_3 #${config.colorScheme.colors.base06};
    @define-color light_4 #${config.colorScheme.colors.base07};
    @define-color light_5 #${config.colorScheme.colors.base08};
    @define-color dark_1 mix(#${config.colorScheme.colors.base01},white,0.5);
    @define-color dark_2 mix(#${config.colorScheme.colors.base01},white,0.2);
    @define-color dark_3 #${config.colorScheme.colors.base01};
    @define-color dark_4 mix(#${config.colorScheme.colors.base01},black,0.2);
    @define-color dark_5 mix(#${config.colorScheme.colors.base01},black,0.4);
  '';

  home.file.".config/gtk-3.0/gtk.css".text = ''
    @define-color accent_color #${config.colorScheme.colors.base0D};
    @define-color accent_bg_color mix(#${config.colorScheme.colors.base0D}, #${config.colorScheme.colors.base01}, 0.3);
    @define-color accent_fg_color #${config.colorScheme.colors.base07};
    @define-color destructive_color #${config.colorScheme.colors.base0D};
    @define-color destructive_bg_color mix(#${config.colorScheme.colors.base0D}, #${config.colorScheme.colors.base01}, 0.3);
    @define-color destructive_fg_color #${config.colorScheme.colors.base07};
    @define-color success_color #${config.colorScheme.colors.base0B};
    @define-color success_bg_color #${config.colorScheme.colors.base0B};
    @define-color success_fg_color #${config.colorScheme.colors.base07};
    @define-color warning_color #${config.colorScheme.colors.base0A};
    @define-color warning_bg_color #${config.colorScheme.colors.base09};
    @define-color warning_fg_color rgba(0, 0, 0, 0.8);
    @define-color error_color #${config.colorScheme.colors.base0F};
    @define-color error_bg_color mix(#${config.colorScheme.colors.base0D}, #${config.colorScheme.colors.base01}, 0.3);
    @define-color error_fg_color #${config.colorScheme.colors.base07};
    @define-color window_bg_color #${config.colorScheme.colors.base01};
    @define-color window_fg_color #${config.colorScheme.colors.base07};
    @define-color view_bg_color #${config.colorScheme.colors.base01};
    @define-color view_fg_color #${config.colorScheme.colors.base07};
    @define-color headerbar_bg_color mix(#${config.colorScheme.colors.base01},black,0.2);
    @define-color headerbar_fg_color #${config.colorScheme.colors.base07};
    @define-color headerbar_border_color #${config.colorScheme.colors.base07};
    @define-color headerbar_backdrop_color @window_bg_color;
    @define-color headerbar_shade_color rgba(0, 0, 0, 0.36);
    @define-color card_bg_color rgba(255, 255, 255, 0.08);
    @define-color card_fg_color #${config.colorScheme.colors.base07};
    @define-color card_shade_color rgba(0, 0, 0, 0.36);
    @define-color dialog_bg_color #${config.colorScheme.colors.base03};
    @define-color dialog_fg_color #${config.colorScheme.colors.base07};
    @define-color popover_bg_color #${config.colorScheme.colors.base03};
    @define-color popover_fg_color #${config.colorScheme.colors.base07};
    @define-color shade_color rgba(0,0,0,0.36);
    @define-color scrollbar_outline_color rgba(0,0,0,0.5);
    @define-color blue_1 #${config.colorScheme.colors.base0D};
    @define-color blue_2 #${config.colorScheme.colors.base0D};
    @define-color blue_3 #${config.colorScheme.colors.base0D};
    @define-color blue_4 #${config.colorScheme.colors.base0D};
    @define-color blue_5 #${config.colorScheme.colors.base0D};
    @define-color green_1 #${config.colorScheme.colors.base0B};
    @define-color green_2 #${config.colorScheme.colors.base0B};
    @define-color green_3 #${config.colorScheme.colors.base0B};
    @define-color green_4 #${config.colorScheme.colors.base0B};
    @define-color green_5 #${config.colorScheme.colors.base0B};
    @define-color yellow_1 #${config.colorScheme.colors.base0A};
    @define-color yellow_2 #${config.colorScheme.colors.base0A};
    @define-color yellow_3 #${config.colorScheme.colors.base0A};
    @define-color yellow_4 #${config.colorScheme.colors.base0A};
    @define-color yellow_5 #${config.colorScheme.colors.base0A};
    @define-color orange_1 #${config.colorScheme.colors.base09};
    @define-color orange_2 #${config.colorScheme.colors.base09};
    @define-color orange_3 #${config.colorScheme.colors.base09};
    @define-color orange_4 #${config.colorScheme.colors.base09};
    @define-color orange_5 #${config.colorScheme.colors.base09};
    @define-color red_1 #${config.colorScheme.colors.base0F};
    @define-color red_2 #${config.colorScheme.colors.base0F};
    @define-color red_3 #${config.colorScheme.colors.base0F};
    @define-color red_4 #${config.colorScheme.colors.base0F};
    @define-color red_5 #${config.colorScheme.colors.base0F};
    @define-color purple_1 #${config.colorScheme.colors.base0E};
    @define-color purple_2 #${config.colorScheme.colors.base0E};
    @define-color purple_3 #${config.colorScheme.colors.base0E};
    @define-color purple_4 #${config.colorScheme.colors.base0E};
    @define-color purple_5 #${config.colorScheme.colors.base0E};
    @define-color brown_1 #${config.colorScheme.colors.base0F};
    @define-color brown_2 #${config.colorScheme.colors.base0F};
    @define-color brown_3 #${config.colorScheme.colors.base0F};
    @define-color brown_4 #${config.colorScheme.colors.base0F};
    @define-color brown_5 #${config.colorScheme.colors.base0F};
    @define-color light_1 #${config.colorScheme.colors.base04};
    @define-color light_2 #${config.colorScheme.colors.base05};
    @define-color light_3 #${config.colorScheme.colors.base06};
    @define-color light_4 #${config.colorScheme.colors.base07};
    @define-color light_5 #${config.colorScheme.colors.base08};
    @define-color dark_1 mix(#${config.colorScheme.colors.base01},white,0.5);
    @define-color dark_2 mix(#${config.colorScheme.colors.base01},white,0.2);
    @define-color dark_3 #${config.colorScheme.colors.base01};
    @define-color dark_4 mix(#${config.colorScheme.colors.base01},black,0.2);
    @define-color dark_5 mix(#${config.colorScheme.colors.base01},black,0.4);
  '';
}
